# Generated by Django 6.1.1 on 2026-10-04 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobListingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('job_url', models.CharField(max_length=1024)),
                ('job_type', models.CharField(blank=True, max_length=1024, null=True)),
                ('level', models.CharField(blank=True, max_length=1024, null=True)),
                ('summary', models.CharField(blank=True, max_length=1024, null=True)),
                ('salary', models.CharField(blank=True, max_length=1024, null=True)),
                ('posted', models.CharField(blank=True, max_length=1024, null=True)),
                ('applicants', models.IntegerField(blank=True, null=True)),
                ('llm_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_listing_results', to='jobs.llmresult')),
            ],
        ),
        migrations.CreateModel(
            name='SearchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('prompt', models.TextField()),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RUNNING', max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='llmresult',
            name='search',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_result', to='jobs.searchinfo'),
        ),
    ]
