# Generated by Django 6.1.1 on 2026-10-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblistingresult',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
