# Generated by Django 6.1.1 on 2026-10-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_joblistingresult_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblistingresult',
            name='source',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='joblistingresult',
            name='job_url',
            field=models.URLField(max_length=1024),
        ),
    ]
